import type { PackDraft } from "./types";

export const examplePack: PackDraft = {
  title: "Harbor dawn",
  logline: "A fisher leaves the dock as the fog lifts.",
  aspect_ratio: "16:9",
  resolution: "720p",
  look_bible: {
    cast: "The same fisher, with the same face and the same body type, in every shot.",
    wardrobe: "The same working coat, boots, and knit cap on the fisher, unchanged.",
    palette: "Cool harbor gray, fog white, weathered wood brown, and muted dawn blue, held constant.",
    lighting: "Soft dawn key, low contrast, fog diffusion, and no hard shadow change between shots.",
    camera: "35mm film still, natural color, one grade, no flicker and no lens change between shots.",
  },
  style_preset: "",
  beat_map: [],
  cast: [],
  staging: null,
  lock_staging: true,
  music_path: "",
  shots: [
    {
      id: "s01",
      prompt_still: "A wooden fishing boat at a quiet harbor, dawn fog, 35mm film still",
      prompt_motion: "The boat eases away from the dock, fog sliding past the lens",
      duration_sec: 8,
      end_state: "The boat is ten meters off the dock, bow pointed toward open water, fog still thick.",
      start_state: "",
      beat: "",
      camera: { scale: "", angle: "", move: "", exit_frame: "" },
      stage: null,
      video_mode: "image_to_video",
      dialogue: "",
      voice_id: "",
    },
    {
      id: "s02",
      prompt_still: "The same fishing boat in open water, fog thinning, same hull",
      prompt_motion: "A slow push in as the fog thins and the bow rises on a swell",
      duration_sec: 8,
      start_state: "The boat is ten meters off the dock, bow pointed toward open water, fog still thick.",
      end_state: "The boat is in open water, fog lifted to the horizon, bow unchanged.",
      beat: "",
      camera: { scale: "", angle: "", move: "", exit_frame: "" },
      stage: null,
      video_mode: "image_to_video",
      dialogue: "",
      voice_id: "",
    },
  ],
};
